config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#home'

  resources :categories do
    resources :products, shallow: true do
      resources :orders
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :products, dependent: :destroy

  has_one_attached :image_uploaded
end

app/models/order.rb
class Order < ApplicationRecord
  SHIRT_SIZE = %w[S M L XL XXL].freeze
  SHOE_SIZE = %w[36 37 38 39 40 41 42 43 44 45].freeze

  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :category
  has_one_attached :image_uploaded
  has_many :orders

  validates :name, :price, presence: true

  def resized_image
      image_uploaded.variant(resize_to_limit: [300, 300]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  def show
    @category = Category.friendly.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_product, only: %i[new create]

  def new
    @order = @product.orders.build
  end

  def create
    @order = @product.orders.build(order_params)
    if @order.save
      OrderMailer.with(order: @order).order_email.deliver_now
      redirect_to @order
    else
      render :new
    end
  end

  def show; end

  private

  def set_product
    @product = Product.friendly.find(params[:product_id])
  end

  def order_params
    params.require(:order).permit(:first_name, :last_name, :email, :phone, :address, :qty, :size)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @categories = Category.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @category = Category.find(params[:id])
    @products = @category.products.all
  end

  def show
    @product = Product.friendly.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
		controller.include?(params[:controller])
	end

	def action?(*action)
		action.include?(params[:action])
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def image_product(product)
    if product.image_url.present?
      product.image_url
    else
      product.image_uploaded
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def size
    if @product.category.name == 'Shirts'
      Order::SHIRT_SIZE
    elsif @product.category.name == 'Shoes'
      Order::SHOE_SIZE
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def image_present(category)
    if category.image.present?
      category.image
    else
      category.image_uploaded
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/show.html.erb
<div class="container pt-3">
  <h2 class="mbr-section-title pb-3 align-center mbr-fonts-style display-5 mt-5">All <%= @category.name %></h2>
  <div class="row pt-5">
    <% @category.products.each do |product| %>
      <div class="card p-2 col-12 col-md-6 col-lg-4 mt-3 mb-3 mr-1 link-to">
    <%= link_to product do %>
        <div class="card-wrapper ">
          <div class="card-img text-center">
            <%= image_tag product.resized_image if product.image_uploaded.attached? %>
          </div>
          <div class="card-box text-center">
            <p class="link-to"><%= product.name %></p>
            <h4 class="card-title mbr-fonts-style display-7 link-to">
              <%= product.price %>MKD
            </h4>
              <%= link_to 'Order Now!', new_product_order_path(product.id), class:"btn btn-success" %>
          </div>
        </div>
      <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <section class="services show-products">
      <%= yield %>
      <%= render 'shared/footer' %>
    </section>
  </body>
</html>

app/views/orders/new.html.erb
<section class="services show-products">
  <div class="container">
    <h1>Order for <%= @product.name %></h1>
    <div class="jumbotron order mt-5" id="result" >
      <div class="row mt-4">
        <div class="col-md mt-4">
          <%= form_with model: [@product, @order], local: true do |f| %>
            <div class="form-row mt-2">
              <div class="col">
                <%= f.label :first_name %>
                <%= f.text_field :first_name, class:"form-control" %>
              </div>
              <div class="col">
                <%= f.label :last_name  %>
                <%= f.text_field :last_name, class:"form-control" %>
              </div>
            </div>
            <div class="form-row mt-2">
              <div class="col">
                <%= f.label :phone, class:"label" %>
                <%= f.text_field :phone, class:"form-control" %>
              </div>
              <div class="col">
                <%= f.label :address %>
                <%= f.text_field :address, class:"form-control" %>
              </div>
            </div>
            <div class="form-row mt-2">
              <div class="col">
                <%= f.label :qty %>
                <%= f.select :qty, options_for_select(1.upto(10)), { default: 1 }, class:"custom-select", data: { controller: "hello", action:"change->hello#value"} %>
              </div>
              <div class="col mb-2">
                <%= f.label :size %>
                <%= f.select :size, options_for_select(Order::SHIRT_SIZE), { prompt: "Ве молиме изберете..."}, class:"custom-select" %>
              </div>
            </div>
          </div>
          <div class="col-md" id="price">
            <h3><%= @product.name %></h3>
            <p><%= image_tag(@product.resized_image) if @product.image_uploaded.attached? %> </p>
            <p><i class="fas fa-tag fa-lg"></i> Цена: <%= @product.price %> Ден</p>
            <p><i class="fas fa-shipping-fast fa-lg"></i> Достава: 130Ден | <span class="text-muted">ИН Пошта Радески</span></p>
          </div>
        </div>
        <div id='score' data-id="<%= @product.price %>">
        </div>
      </div>
      <%= f.submit "НАРАЧАЈ", class:"btn btn-primary btn-lg btn-block mt-4" %>
    <% end %>
  </div>
</section>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/pages/home.html.erb
<!-- ======= Hero Section ======= -->
<section id="hero" class="d-flex justify-cntent-center align-items-center">
  <div id="heroCarousel" class="container carousel carousel-fade" data-ride="carousel">
    <!-- Slide 1 -->
    <div class="carousel-item active">
      <div class="carousel-container">
        <h2 class="animate__animated animate__fadeInDown">Добро дојдовте <span>МОДЕРНО</span></h2>
        <p class="animate__animated animate__fadeInUp">Производи и принтови со најквалитетен материјал.</p>
        <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
      </div>
    </div>
    <%# <!-- Slide 2 -->
    <div class="carousel-item">
      <div class="carousel-container">
        <h2 class="animate__animated animate__fadeInDown">Lorem Ipsum Dolor</h2>
        <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
        <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
      </div>
    </div>
    <!-- Slide 3 -->
    <div class="carousel-item">
      <div class="carousel-container">
        <h2 class="animate__animated animate__fadeInDown">Sequi ea ut et est quaerat</h2>
        <p class="animate__animated animate__fadeInUp">Ut velit est quam dolor ad a aliquid qui aliquid. Sequi ea ut et est quaerat sequi nihil ut aliquam. Occaecati alias dolorem mollitia ut. Similique ea voluptatem. Esse doloremque accusamus repellendus deleniti vel. Minus et tempore modi architecto.</p>
        <a href="" class="btn-get-started animate__animated animate__fadeInUp">Read More</a>
      </div>
    </div>
    <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon bx bx-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon bx bx-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a> %>
  </div>
</section>
<!-- End Hero -->
<main id="main">
  <!-- ======= Services Section ======= -->
  <section class="services">
    <div class="container">
      <div class="row">
        <div class="row">
          <% @categories.each do |category| %>
            <div class="col-md-6 col-lg-3 d-flex align-items" data-aos="fade-up" data-aos-delay="200">
              <div class="icon-box">
               <div>
                <%= image_tag category.image_uploaded, class:"rounded-circle main bx bx-world" %>
               <i class="bx bx-world"></i></div>
                <h4 class="title mt-2"><%= link_to category.name, category_path(category) %></h4>
                <%= link_to 'View all', category_path(category), class:"btn btn-primary" %>
                <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque</p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </section>
    <!-- End Services Section -->
    <!-- ======= Why Us Section ======= -->
    <section class="why-us section-bg" data-aos="fade-up" date-aos-delay="200">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 video-box">
            <img src="assets/img/why-us.jpg" class="img-fluid" alt="">
            <a href="https://www.youtube.com/watch?v=jDDaplaOz7Q" class="venobox play-btn mb-4" data-vbtype="video" data-autoplay="true"></a>
          </div>
          <div class="col-lg-6 d-flex flex-column justify-content-center p-5">
            <div class="icon-box">
              <div class="icon"><i class="bx bx-fingerprint"></i></div>
              <h4 class="title"><a href="">Lorem Ipsum</a></h4>
              <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident</p>
            </div>
            <div class="icon-box">
              <div class="icon"><i class="bx bx-gift"></i></div>
              <h4 class="title"><a href="">Nemo Enim</a></h4>
              <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque</p>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End Why Us Section -->
    <!-- ======= Features Section ======= -->
    <section class="features">
      <div class="container">
        <div class="section-title">
          <h2>Features</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
        </div>
        <div class="row" data-aos="fade-up">
          <div class="col-md-5">
            <img src="assets/img/features-1.svg" class="img-fluid" alt="">
          </div>
          <div class="col-md-7 pt-4">
            <h3>Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.</h3>
            <p class="font-italic">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua.
            </p>
            <ul>
              <li><i class="icofont-check"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
              <li><i class="icofont-check"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
            </ul>
          </div>
        </div>
        <div class="row" data-aos="fade-up">
          <div class="col-md-5 order-1 order-md-2">
            <img src="assets/img/features-2.svg" class="img-fluid" alt="">
          </div>
          <div class="col-md-7 pt-5 order-2 order-md-1">
            <h3>Corporis temporibus maiores provident</h3>
            <p class="font-italic">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua.
            </p>
            <p>
              Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
              velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
              culpa qui officia deserunt mollit anim id est laborum
            </p>
          </div>
        </div>
        <div class="row" data-aos="fade-up">
          <div class="col-md-5">
            <img src="assets/img/features-3.svg" class="img-fluid" alt="">
          </div>
          <div class="col-md-7 pt-5">
            <h3>Sunt consequatur ad ut est nulla consectetur reiciendis animi voluptas</h3>
            <p>Cupiditate placeat cupiditate placeat est ipsam culpa. Delectus quia minima quod. Sunt saepe odit aut quia voluptatem hic voluptas dolor doloremque.</p>
            <ul>
              <li><i class="icofont-check"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
              <li><i class="icofont-check"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
              <li><i class="icofont-check"></i> Facilis ut et voluptatem aperiam. Autem soluta ad fugiat.</li>
            </ul>
          </div>
        </div>
        <div class="row" data-aos="fade-up">
          <div class="col-md-5 order-1 order-md-2">
            <img src="assets/img/features-4.svg" class="img-fluid" alt="">
          </div>
          <div class="col-md-7 pt-5 order-2 order-md-1">
            <h3>Quas et necessitatibus eaque impedit ipsum animi consequatur incidunt in</h3>
            <p class="font-italic">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua.
            </p>
            <p>
              Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
              velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
              culpa qui officia deserunt mollit anim id est laborum
            </p>
          </div>
        </div>
      </div>
    </section>
    <!-- End Features Section -->
  </main><!-- End #main -->
  

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/products/show.html.erb
<div class="container pt-3">
  <div class="jumbotron text-center">
    <div class="row">
      <div class="col">
        <h3><%= @product.name.upcase %></h3>
        <%= image_tag @product.resized_image %>
        <p><%= @product.price %> </p>
      </div>
      <div class="col">
        <h4><%= "Опис за производот(#{@product.name})" %></h4>
        <%= @product.description %>
      </div>  
    </div>
        <%= link_to "НАРАЧАЈ", new_product_order_path(@product), class:"btn btn-success" %>
  </div>  
  
</div>

app/views/shared/_footer.html.erb
  <footer id="footer" data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="500">
    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>
          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>
          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br>
              <br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>
          <div class="col-lg-3 col-md-6 footer-info">
            <h3>About Moderna</h3>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Igor Petrovski</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer>

app/views/shared/_navbar.html.erb
  <header id="header" class="fixed-top header-transparent">
    <div class="container">

      <div class="logo float-left">
        <h1 class="text-light"><a href="<%= root_path %>"><span>Moderno</span></a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
      </div>

      <nav class="nav-menu float-right d-none d-lg-block">
        <ul>
          <li class="active"><a href="index.html">Почетна</a></li>
          <li class="drop-down"><a href="">Производи</a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="drop-down"><a href="#">Drop Down 2</a>
              </li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
              <li><a href="#">Drop Down 5</a></li>
            </ul>
          </li>
          <li><a href="services.html">За нас</a></li>
          <li><a href="portfolio.html">Контакт</a></li>
        </ul>
      </nav><!-- .nav-menu -->

    </div>
    <div class="row">
        <%= render 'shared/navigation' %>
    </div>
  </header><!-- End Header -->

app/views/shared/_navigation.html.erb
<div navinavi>
  <span>
    <%= link_to root_path do %>
      <i class="fas fa-home"></i>
    <% end %>
  </span>
  <span class="<%= 'navmenu-hidden' unless controller?('categories') && action?('show')%>"> > <%= link_to @category.name, category_path if controller?('categories') && action?('show') %> </span>
  <span class="<%= 'navmenu-hidden' unless controller?('orders') && action?('new')%>"> > <%= link_to @order.product.category.name, category_path(@order.product.category.id)  if controller?('orders') && action?('new') %> > Нарачка </span>
</div>